[package]
name = "katakomb"
version = "0.1.0"
authors = ["CodeBunny <slayer111315@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
noise = "0.6.0"
ndarray = { version = "0.13.0", features = ["rayon", "serde"] }
rand = "0.7.3"
rayon = "1.3.0"
rodio = "0.11.0"
image = "0.23.0"
na = { version = "0.19.0", package = "nalgebra" }
serde = { version = "1.0.106", features = ["derive"] }
internship = "0.6.0"
